# PreToolUse hook: block writes to paths where a mistake is silent.
# Exit 2 blocks the call and shows stderr to Claude. Odd input exits 0: a hook
# that fails closed would block every edit.

from __future__ import annotations

import json
import sys
from pathlib import Path

WRITE_TOOLS = {"Write", "Edit", "NotebookEdit"}

PROTECTED = {
    ".claude/skills/": (
        "a skill here is resolved by `npx skills add` and ships to users. "
        "Author product skills in src/opik_mcp/skills/ instead; dev procedures "
        "go in .claude/commands/."
    ),
    ".agents/skills/": (
        "a skill here is resolved by `npx skills add` and ships to users. "
        "Author product skills in src/opik_mcp/skills/ instead."
    ),
    "src/opik_mcp/_version.py": (
        "_version.py is generated by `make version`. Change version.txt instead."
    ),
    "dist/": "dist/ is build output. Change the source and rebuild instead.",
}


def _repo_root(path: Path) -> Path | None:
    # `.git` is a file in a worktree, so a worktree is judged by its own root.
    for parent in path.parents:
        if (parent / ".git").exists():
            return parent
    return None


def main() -> int:
    try:
        call = json.load(sys.stdin)
    except ValueError:
        return 0
    if call.get("tool_name") not in WRITE_TOOLS:
        return 0
    tool_input = call.get("tool_input") or {}
    raw = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not raw:
        return 0
    path = Path(raw).resolve()
    root = _repo_root(path)
    if root is None:
        return 0
    relative = path.relative_to(root).as_posix()
    for prefix, reason in PROTECTED.items():
        if relative.startswith(prefix):
            print(f"Blocked write to {relative}: {reason}", file=sys.stderr)
            return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
