"""Does this deployment have Diagnostics at all?

Diagnostics reports are generated by Ollie. A deployment without Ollie still
answers every agent-insights endpoint: the issue list is empty, a job can be
created, and a trigger is queued to a stream no consumer reads, so the scan
never runs and the job never records a failure. Nothing in the data says
"this will never work".

The one honest signal is the backend's own service toggle, the same one the
UI reads to decide whether to show the Diagnostics page. This module reads it
on the paths that would otherwise promise a scan that cannot happen: an empty
issue list, and the two job write operations.

Read fresh every time. The gate is only consulted for Diagnostics work — a
handful of calls in a session, against a cheap toggles endpoint — so a cache
would trade a live answer for savings nobody measures, and an operator
switching Ollie on mid-session sees it at once.

Failing open is deliberate: a toggles endpoint that errors, or a backend too
old to carry the field, must leave today's behaviour intact rather than
declare a working feature unavailable.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from opik_mcp.opik_client import (
    OpikAuthError,
    OpikListClient,
    OpikNotFoundError,
    OpikServerError,
    OpikValidationError,
)

logger = logging.getLogger("opik_mcp.read_list.deployment")

# The backend declares the field as ``ollieEnabled``; the UI's toggle key is
# ``ollie_enabled``. Accept both so neither side's spelling is load-bearing.
_OLLIE_FIELDS = ("ollieEnabled", "ollie_enabled")

UNAVAILABLE_SENTENCE = (
    "Diagnostics is not available on this deployment (Ollie is off); it cannot "
    "be enabled through the MCP."
)


async def diagnostics_available(client: OpikListClient) -> bool:
    """Is Diagnostics available on this deployment? Fails open."""
    try:
        toggles: dict[str, Any] = await client.get_service_toggles()
    except (
        OpikAuthError,
        OpikNotFoundError,
        OpikValidationError,
        OpikServerError,
        httpx.HTTPError,
    ):
        logger.debug("service toggles lookup failed; assuming Diagnostics is available")
        return True

    for field in _OLLIE_FIELDS:
        if field in toggles:
            return bool(toggles[field])
    return True


__all__ = ["UNAVAILABLE_SENTENCE", "diagnostics_available"]
