"""Does this deployment have Diagnostics at all?

Diagnostics reports are generated by Ollie. A deployment without Ollie still
answers every agent-insights endpoint: the issue list is empty, a job can be
created, and a trigger is queued to a stream no consumer reads, so the scan
never runs and the job never records a failure. Nothing in the data says
"this will never work".

The one honest signal is the backend's own service toggle, the same one the
UI reads to decide whether to show the Diagnostics page. This module reads it
and remembers the answer for the process, so the gate costs one request per
deployment rather than one per call.

Failing open is deliberate: a toggles endpoint that errors, or a backend too
old to carry the field, must leave today's behaviour intact rather than
declare a working feature unavailable.
"""

from __future__ import annotations

import hashlib
import logging
import time
from typing import Any

import httpx

from opik_mcp.opik_client import (
    OpikAuthError,
    OpikListClient,
    OpikNotFoundError,
    OpikServerError,
    OpikValidationError,
)

logger = logging.getLogger("opik_mcp.read_list.deployment")

# The backend declares the field as ``ollieEnabled``; the UI's toggle key is
# ``ollie_enabled``. Accept both so neither side's spelling is load-bearing.
_OLLIE_FIELDS = ("ollieEnabled", "ollie_enabled")

# A deployment's feature set does not change under a running session, so this
# could live forever; a few minutes keeps a mid-session rollout visible.
_CACHE_TTL_SECONDS = 300.0
_CACHE_MAX_ENTRIES = 64
_CacheKey = tuple[str | None, str | None]
_cache: dict[_CacheKey, tuple[bool, float]] = {}

UNAVAILABLE_SENTENCE = (
    "Diagnostics is not available on this deployment (Ollie is off); it cannot "
    "be enabled through the MCP."
)


def _cache_key(client: OpikListClient) -> _CacheKey:
    base_url = getattr(client, "_base_url", None)
    credential = getattr(client, "_api_key", None)
    credential_hash = (
        hashlib.sha256(credential.encode()).hexdigest()[:16]
        if isinstance(credential, str) and credential
        else None
    )
    return (base_url if isinstance(base_url, str) and base_url else None, credential_hash)


def reset_deployment_cache_for_tests() -> None:
    """Drop the cached toggles. Test-only: fakes carry no config, so they all
    share one key and one test's answer would satisfy the next."""
    _cache.clear()


async def diagnostics_available(client: OpikListClient) -> bool:
    """Is Diagnostics available on this deployment? Fails open."""
    key = _cache_key(client)
    hit = _cache.get(key)
    if hit is not None:
        available, expires_at = hit
        if time.monotonic() < expires_at:
            return available
        _cache.pop(key, None)

    try:
        toggles: dict[str, Any] = await client.get_service_toggles()
    except (
        OpikAuthError,
        OpikNotFoundError,
        OpikValidationError,
        OpikServerError,
        httpx.HTTPError,
    ):
        # Not cached: the next call retries rather than inheriting a guess.
        logger.debug("service toggles lookup failed; assuming Diagnostics is available")
        return True

    available = True
    for field in _OLLIE_FIELDS:
        if field in toggles:
            available = bool(toggles[field])
            break

    if len(_cache) >= _CACHE_MAX_ENTRIES:
        _cache.pop(next(iter(_cache)), None)
    _cache[key] = (available, time.monotonic() + _CACHE_TTL_SECONDS)
    return available


__all__ = [
    "UNAVAILABLE_SENTENCE",
    "diagnostics_available",
    "reset_deployment_cache_for_tests",
]
