# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci --ignore-scripts

COPY . .
RUN npm run build
RUN npm prune --omit=dev --ignore-scripts

FROM node:lts-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/build ./build

EXPOSE 3001

ENV NODE_ENV=production \
    STREAMABLE_HTTP_HOST=0.0.0.0 \
    STREAMABLE_HTTP_PORT=3001 \
    OPIK_TOOLSETS=all

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget -q -O /dev/null "http://127.0.0.1:${STREAMABLE_HTTP_PORT:-3001}/health" || exit 1

USER node

CMD ["node", "build/cli.js", "serve", "--transport", "streamable-http"]
