# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies without running any scripts
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# Expose default MCP port for streamable-http transport
EXPOSE 3001

# Default to streamable-http transport in Docker deployments
ENV STREAMABLE_HTTP_HOST=0.0.0.0 \
    OPIK_TOOLSETS=all
CMD ["node", "build/cli.js", "serve", "--transport", "streamable-http", "--port", "3001"]
