"""What the published wheel actually contains — built, not assumed.

`tests/test_skills_packaged.py` resolves the skills through `importlib.resources`,
which in a dev checkout reads the EDITABLE install: it points at `src/`, so it
passes whatever the build backend would or would not put in a wheel. Nothing else
in the suite looks at a built artifact at all.

That gap shipped a real defect. The `opik-diagnose` and `opik-explain` skills
carry `evals/` fixture directories; `skills_catalog.EXCLUDED_DIRS` keeps them off
both MCP surfaces and `build_skills_pack.py` keeps them out of the published
pack — but no rule kept them out of the wheel. 0.2.24 was clean only because it
predates those two skills, so the next release would have been the first to put
41 KB of fixtures, including runnable `agent.py` / `seed.py` / `grader.py`, into
every user's site-packages.

These tests build a real wheel with the real backend and read it back. Marked
`e2e` because they shell out to `uv build` (a few seconds) and because, like the
stdio suite, the thing under test only exists once something is really executed.
"""

from __future__ import annotations

import shutil
import subprocess
import zipfile
from pathlib import Path

import pytest

from opik_mcp.skills_catalog import EXCLUDED_DIRS, iter_skill_files, skill_names

REPO_ROOT = Path(__file__).resolve().parents[2]

#: `uv` is a standalone binary, not an importable module — `python -m uv` does
#: not work even in an environment uv itself created. CI always has it (the
#: `setup-uv` step puts it on PATH); a checkout without it skips rather than
#: fails, since a missing dev tool is not a defect in the package.
UV = shutil.which("uv")
pytestmark = pytest.mark.skipif(UV is None, reason="uv is not on PATH")


@pytest.fixture(scope="module")
def wheel(tmp_path_factory: pytest.TempPathFactory) -> zipfile.ZipFile:
    """One wheel built with the real backend, shared by the tests below.

    `uv build` needs `_version.py`, which is git-ignored and generated by
    `make version`. A dev checkout always has one (nothing imports without it),
    so this asserts rather than generates: writing it here could mask a broken
    version step in the release path.
    """
    assert (REPO_ROOT / "src" / "opik_mcp" / "_version.py").is_file(), (
        "_version.py missing — run `make version` (CI does this before any build)"
    )
    out = tmp_path_factory.mktemp("wheel")
    result = subprocess.run(
        [str(UV), "build", "--wheel", "-o", str(out)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert result.returncode == 0, f"uv build failed:\n{result.stdout}\n{result.stderr}"
    built = sorted(out.glob("*.whl"))
    assert len(built) == 1, f"expected exactly one wheel, got {built}"
    return zipfile.ZipFile(built[0])


def _skill_entries(wheel: zipfile.ZipFile) -> list[str]:
    return [n for n in wheel.namelist() if "/skills/" in n]


@pytest.mark.e2e
def test_every_served_skill_document_is_in_the_wheel(wheel: zipfile.ZipFile) -> None:
    """The tool and the resource surface both read through `importlib.resources`,
    so a document missing from the wheel is a document the released server cannot
    serve — `read_skill` would fail at runtime for a user who pip-installed it,
    while every in-repo test stayed green."""
    packaged = set(_skill_entries(wheel))
    for entry in iter_skill_files():
        expected = f"opik_mcp/skills/{entry.skill}/{entry.path}"
        assert expected in packaged, f"{expected} is served but not in the wheel"


@pytest.mark.e2e
def test_the_wheel_carries_nothing_the_server_will_not_serve(wheel: zipfile.ZipFile) -> None:
    """The other direction, which is the one that regressed. Anything under
    `skills/` that `EXCLUDED_DIRS` filters is dead weight in site-packages —
    and `evals/` is not inert dead weight, it is runnable fixture code."""
    served = {f"opik_mcp/skills/{f.skill}/{f.path}" for f in iter_skill_files()}
    stowaways = [n for n in _skill_entries(wheel) if not n.endswith("/") and n not in served]
    assert not stowaways, (
        f"the wheel ships {len(stowaways)} skill files the server never serves: "
        f"{sorted(stowaways)[:5]}"
    )


@pytest.mark.e2e
@pytest.mark.parametrize("excluded", sorted(EXCLUDED_DIRS))
def test_excluded_directories_never_reach_the_wheel(wheel: zipfile.ZipFile, excluded: str) -> None:
    """Named per directory so a failure says which rule broke."""
    leaked = [n for n in wheel.namelist() if f"/{excluded}/" in n]
    assert not leaked, f"{excluded}/ leaked into the wheel: {sorted(leaked)[:5]}"


@pytest.mark.e2e
def test_the_wheel_is_importable_and_serves_skills_from_it(
    wheel: zipfile.ZipFile, tmp_path: Path
) -> None:
    """The end of the chain: install the built wheel into a throwaway env and ask
    THAT interpreter to enumerate the skills. Proves the packaged data is reachable
    through `importlib.resources` from a real installation, which is the only thing
    a pip-installing user actually has."""
    built = wheel.filename
    assert built is not None, "the wheel fixture did not record a path on disk"
    env = tmp_path / "venv"
    subprocess.run([str(UV), "venv", str(env)], check=True, capture_output=True)
    python = env / "bin" / "python"
    subprocess.run(
        [str(UV), "pip", "install", "--python", str(python), built],
        check=True,
        capture_output=True,
        timeout=300,
    )
    probe = subprocess.run(
        [
            str(python),
            "-c",
            "from opik_mcp.skills_catalog import iter_skill_files, skill_names; "
            "print(len(iter_skill_files()), ','.join(skill_names()))",
        ],
        capture_output=True,
        text=True,
        timeout=120,
    )
    assert probe.returncode == 0, f"installed wheel could not enumerate skills:\n{probe.stderr}"
    count, names = probe.stdout.strip().split(" ", 1)
    assert int(count) == len(iter_skill_files())
    assert names.split(",") == list(skill_names())
