name: Bug Report
description: Report a defect in opik-mcp
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please provide enough detail to reproduce the issue.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Include commands/configuration and expected vs actual behavior.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, Node version, transport mode, and client (Cursor/VS Code/etc.).
